### ISSUE TITLE
Server Error: SQLSTATE[22007]: Invalid datetime format

### ISSUE THREAD

**Issue by arekdist** [munkireport/findmymac#6]
Following error occurs on machine without any findmymac config:
```
Server An error occurred while processing: \Findmymac_model
Server Error: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `munkireport`.`findmymac`.`add_time` at row 1
Server info: starting: findmymac
```

**Comment by anotherpekka** [comment]
> Following error occurs on machine without any findmymac config:
> 
> ```
> Server An error occurred while processing: \Findmymac_model
> Server Error: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `munkireport`.`findmymac`.`add_time` at row 1
> Server info: starting: findmymac
> ```

One workaround is to add some date (in unix time integer format) after the "disabled" line in findmymac.sh :
```
echo "Status = Disabled" > "$findmymac_manfiest_file"  
echo "add_time = 0" >> "$findmymac_manfiest_file"  
# 1970-01-01
```

Or current time, but as that updates at every check so it doesn't do any good.

**Comment by tuxudo** [comment]
This has been fixed, will release a new module for it soon
